/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import '@stencil/core';




export namespace Components {

  interface MyComponent {
    /**
    * The first name
    */
    'first': string;
    /**
    * The last name
    */
    'last': string;
    /**
    * The middle name
    */
    'middle': string;
  }
  interface MyComponentAttributes extends StencilHTMLAttributes {
    /**
    * The first name
    */
    'first'?: string;
    /**
    * The last name
    */
    'last'?: string;
    /**
    * The middle name
    */
    'middle'?: string;
  }

  interface PlusMinusButtonComponent {
    'border': number;
    'desc': string;
    'getCount': () => Promise<number>;
    'max': number;
    'min': number;
  }
  interface PlusMinusButtonComponentAttributes extends StencilHTMLAttributes {
    'border'?: number;
    'desc'?: string;
    'max'?: number;
    'min'?: number;
    'onOnChanged'?: (event: CustomEvent) => void;
  }
}

declare global {
  interface StencilElementInterfaces {
    'MyComponent': Components.MyComponent;
    'PlusMinusButtonComponent': Components.PlusMinusButtonComponent;
  }

  interface StencilIntrinsicElements {
    'my-component': Components.MyComponentAttributes;
    'plus-minus-button-component': Components.PlusMinusButtonComponentAttributes;
  }


  interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {}
  var HTMLMyComponentElement: {
    prototype: HTMLMyComponentElement;
    new (): HTMLMyComponentElement;
  };

  interface HTMLPlusMinusButtonComponentElement extends Components.PlusMinusButtonComponent, HTMLStencilElement {}
  var HTMLPlusMinusButtonComponentElement: {
    prototype: HTMLPlusMinusButtonComponentElement;
    new (): HTMLPlusMinusButtonComponentElement;
  };

  interface HTMLElementTagNameMap {
    'my-component': HTMLMyComponentElement
    'plus-minus-button-component': HTMLPlusMinusButtonComponentElement
  }

  interface ElementTagNameMap {
    'my-component': HTMLMyComponentElement;
    'plus-minus-button-component': HTMLPlusMinusButtonComponentElement;
  }


  export namespace JSX {
    export interface Element {}
    export interface IntrinsicElements extends StencilIntrinsicElements {
      [tagName: string]: any;
    }
  }
  export interface HTMLAttributes extends StencilHTMLAttributes {}

}
